[project]
name = "natural-selection-simulator"
version = "0.4.5"
description = "Natural Selection Simulator"
readme = "ReadMe.md"
requires-python = ">=3.10"
dependencies = [
    "imageio>=2.37.4",
    "imageio-ffmpeg>=0.6.0",
    "matplotlib",
    "neat-python>=2.0.0",
    "numpy",
    "pygame",
    "ruff>=0.16.5",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

