[project]
name = "natural-selection-simulator"
version = "0.4.5"
description = "Natural Selection Simulator"
readme = "ReadMe.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "neat-python>=2.0.0",
    "numpy",
    "pygame",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
